spring:
  application:
    name: playground

  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/projects/playground/playgroundDB
    username: master
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: "%h %l %u %t \"%r\" %s %b %D"

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace